/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Proceso;
import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class ColaProcesos extends javax.swing.JFrame {

    /**
     * Creates new form ColaProcesos
     */
    private int procesos = 4;
    private int algoritmo;
    private PlanificadorProcesos planificador;
    JTextField campos[] = new JTextField[24];
    private ArrayList<Proceso> listaProcesos;
    
    public ColaProcesos(PlanificadorProcesos planificador, int algoritmo) {
        
        initComponents();
        //Evitar el cierre de la ventaa principal
        this.setDefaultCloseOperation(1);
        
        //Declaramos los elementos a utilizar
        this.planificador = planificador;
        this.algoritmo = algoritmo;
        this.campos = new JTextField[24];
        this.listaProcesos = new ArrayList();
                
        //Agregamos los jTextFields al Array
        this.campos[0] = this.A1;
        this.campos[1] = this.A2;
        this.campos[2] = this.A3;

        this.campos[3] = this.B1;
        this.campos[4] = this.B2;
        this.campos[5] = this.B3;

        this.campos[6] = this.C1;
        this.campos[7] = this.C2;
        this.campos[8] = this.C3;

        this.campos[9] = this.D1;
        this.campos[10] = this.D2;
        this.campos[11] = this.D3;

        this.campos[12] = this.E1;
        this.campos[13] = this.E2;
        this.campos[14] = this.E3;

        this.campos[15] = this.F1;
        this.campos[16] = this.F2;
        this.campos[17] = this.F3;

        this.campos[18] = this.G1;
        this.campos[19] = this.G2;
        this.campos[20] = this.G3;

        this.campos[21] = this.H1;
        this.campos[22] = this.H2;
        this.campos[23] = this.H3;
        
        this.E1.setVisible(false);
        this.E2.setVisible(false);
        this.F1.setVisible(false);
        this.F2.setVisible(false);
        this.G1.setVisible(false);
        this.G2.setVisible(false);
        this.H1.setVisible(false);
        this.H2.setVisible(false);
        this.E3.setVisible(false);
        this.F3.setVisible(false);
        this.G3.setVisible(false);
        this.H3.setVisible(false);
        this.jLabel5.setVisible(false);
        this.jLabel6.setVisible(false);
        this.jLabel7.setVisible(false);
        this.jLabel8.setVisible(false);
        
        if(this.algoritmo!=3){
            this.A3.setVisible(false);
            this.B3.setVisible(false);
            this.C3.setVisible(false);
            this.D3.setVisible(false);
            this.jLabel11.setVisible(false);
        }
        this.jButton2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A1 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        A3 = new javax.swing.JTextField();
        B1 = new javax.swing.JTextField();
        B2 = new javax.swing.JTextField();
        B3 = new javax.swing.JTextField();
        C1 = new javax.swing.JTextField();
        C2 = new javax.swing.JTextField();
        C3 = new javax.swing.JTextField();
        D1 = new javax.swing.JTextField();
        D2 = new javax.swing.JTextField();
        D3 = new javax.swing.JTextField();
        E1 = new javax.swing.JTextField();
        E2 = new javax.swing.JTextField();
        E3 = new javax.swing.JTextField();
        F1 = new javax.swing.JTextField();
        F2 = new javax.swing.JTextField();
        F3 = new javax.swing.JTextField();
        G1 = new javax.swing.JTextField();
        G2 = new javax.swing.JTextField();
        G3 = new javax.swing.JTextField();
        H1 = new javax.swing.JTextField();
        H2 = new javax.swing.JTextField();
        H3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cola de Procesos");
        setMinimumSize(new java.awt.Dimension(360, 300));
        setPreferredSize(new java.awt.Dimension(405, 670));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        A1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        A1.setMaximumSize(new java.awt.Dimension(80, 30));
        A1.setMinimumSize(new java.awt.Dimension(30, 30));
        A1.setPreferredSize(new java.awt.Dimension(80, 30));
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        A1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                A1PropertyChange(evt);
            }
        });
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        A1.getAccessibleContext().setAccessibleName("");

        A2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        A2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        A2.setMaximumSize(new java.awt.Dimension(80, 30));
        A2.setMinimumSize(new java.awt.Dimension(30, 30));
        A2.setPreferredSize(new java.awt.Dimension(80, 30));
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        getContentPane().add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        A3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        A3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        A3.setMaximumSize(new java.awt.Dimension(80, 30));
        A3.setMinimumSize(new java.awt.Dimension(30, 30));
        A3.setPreferredSize(new java.awt.Dimension(80, 30));
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        getContentPane().add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        B1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        B1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        B1.setMaximumSize(new java.awt.Dimension(80, 30));
        B1.setMinimumSize(new java.awt.Dimension(30, 30));
        B1.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        B2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        B2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        B2.setMaximumSize(new java.awt.Dimension(80, 30));
        B2.setMinimumSize(new java.awt.Dimension(30, 30));
        B2.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        B3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        B3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        B3.setMaximumSize(new java.awt.Dimension(80, 30));
        B3.setMinimumSize(new java.awt.Dimension(30, 30));
        B3.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        C1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        C1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        C1.setMaximumSize(new java.awt.Dimension(80, 30));
        C1.setMinimumSize(new java.awt.Dimension(30, 30));
        C1.setPreferredSize(new java.awt.Dimension(80, 30));
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        C2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        C2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        C2.setMaximumSize(new java.awt.Dimension(80, 30));
        C2.setMinimumSize(new java.awt.Dimension(30, 30));
        C2.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        C3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        C3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        C3.setMaximumSize(new java.awt.Dimension(80, 30));
        C3.setMinimumSize(new java.awt.Dimension(30, 30));
        C3.setPreferredSize(new java.awt.Dimension(80, 30));
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        getContentPane().add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        D1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        D1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        D1.setMaximumSize(new java.awt.Dimension(80, 30));
        D1.setMinimumSize(new java.awt.Dimension(30, 30));
        D1.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        D2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        D2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        D2.setMaximumSize(new java.awt.Dimension(80, 30));
        D2.setMinimumSize(new java.awt.Dimension(30, 30));
        D2.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        D3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        D3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        D3.setMaximumSize(new java.awt.Dimension(80, 30));
        D3.setMinimumSize(new java.awt.Dimension(30, 30));
        D3.setPreferredSize(new java.awt.Dimension(80, 30));
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        E1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        E1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        E1.setMaximumSize(new java.awt.Dimension(80, 30));
        E1.setMinimumSize(new java.awt.Dimension(30, 30));
        E1.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        E2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        E2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        E2.setMaximumSize(new java.awt.Dimension(80, 30));
        E2.setMinimumSize(new java.awt.Dimension(30, 30));
        E2.setPreferredSize(new java.awt.Dimension(80, 30));
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        E3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        E3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        E3.setMaximumSize(new java.awt.Dimension(80, 30));
        E3.setMinimumSize(new java.awt.Dimension(30, 30));
        E3.setPreferredSize(new java.awt.Dimension(80, 30));
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        F1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        F1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        F1.setMaximumSize(new java.awt.Dimension(80, 30));
        F1.setMinimumSize(new java.awt.Dimension(30, 30));
        F1.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        F2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        F2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        F2.setMaximumSize(new java.awt.Dimension(80, 30));
        F2.setMinimumSize(new java.awt.Dimension(30, 30));
        F2.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        F3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        F3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        F3.setMaximumSize(new java.awt.Dimension(80, 30));
        F3.setMinimumSize(new java.awt.Dimension(30, 30));
        F3.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        G1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        G1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        G1.setMaximumSize(new java.awt.Dimension(80, 30));
        G1.setMinimumSize(new java.awt.Dimension(30, 30));
        G1.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        G2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        G2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        G2.setMaximumSize(new java.awt.Dimension(80, 30));
        G2.setMinimumSize(new java.awt.Dimension(30, 30));
        G2.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        G3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        G3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        G3.setMaximumSize(new java.awt.Dimension(80, 30));
        G3.setMinimumSize(new java.awt.Dimension(30, 30));
        G3.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        H1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        H1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        H1.setMaximumSize(new java.awt.Dimension(80, 30));
        H1.setMinimumSize(new java.awt.Dimension(30, 30));
        H1.setPreferredSize(new java.awt.Dimension(80, 30));
        getContentPane().add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        H2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        H2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        H2.setMaximumSize(new java.awt.Dimension(80, 30));
        H2.setMinimumSize(new java.awt.Dimension(30, 30));
        H2.setPreferredSize(new java.awt.Dimension(80, 30));
        H2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2ActionPerformed(evt);
            }
        });
        getContentPane().add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        H3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        H3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        H3.setMaximumSize(new java.awt.Dimension(80, 30));
        H3.setMinimumSize(new java.awt.Dimension(30, 30));
        H3.setPreferredSize(new java.awt.Dimension(80, 30));
        H3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H3ActionPerformed(evt);
            }
        });
        getContentPane().add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("+ Agregar proceso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 300, 40));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("- Eliminar proceso");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 300, 40));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Confirmar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 300, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("D");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("E");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("F");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText("G");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("H");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("T. Llegada");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("T. CPU");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Prioridad");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("LISTADO DE PROCESOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 50));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ingrese los valores de los procesos que desea agregar a la");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, 20));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(" lista de procesos");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E3ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D3ActionPerformed

    private void H2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H2ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E2ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void H3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        this.planificador.modelo = new DefaultTableModel();
        this.planificador.modelo.addColumn("Proceso");
        this.planificador.modelo.addColumn("T. Llegada");
        this.planificador.modelo.addColumn("T. CPU");
        this.planificador.modelo.addColumn("T. Comienzo");
        this.planificador.modelo.addColumn("T. Finaliza");
        this.planificador.modelo.addColumn("T. Espera");
        
        this.planificador.modelo1 = new DefaultTableModel();
        this.planificador.modelo1.addColumn("Proceso");
        this.planificador.modelo1.addColumn("T. Llegada");
        this.planificador.modelo1.addColumn("T. CPU");
        this.planificador.modelo1.addColumn("Prioridad");
        this.planificador.modelo1.addColumn("T. Comienzo");
        this.planificador.modelo1.addColumn("T. Finaliza");
        this.planificador.modelo1.addColumn("T. Espera");
        
        for(int x = 0 ; x < procesos*3 ; x+=3){
            if(this.algoritmo == 3){
                this.listaProcesos.add(
                    new Proceso( 
                        Integer.parseInt(this.campos[x].getText()), 
                        Integer.parseInt(this.campos[x+1].getText()), 
                        Integer.parseInt(this.campos[x+2].getText())
                    )
                );
            } else {
                this.listaProcesos.add(
                    new Proceso( 
                        Integer.parseInt(this.campos[x].getText()), 
                        Integer.parseInt(this.campos[x+1].getText())
                    )
                );
            }
        }
        this.planificador.setData(this.listaProcesos);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void A1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_A1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_A1PropertyChange

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.procesos == 4) {
            this.procesos++;
            this.E1.setVisible(true);
            this.E2.setVisible(true);
            this.jLabel5.setVisible(true);
            if(this.algoritmo==3){
                this.E3.setVisible(true);
            }
            this.jButton2.setEnabled(true);            
        } else if (this.procesos == 5) {
            this.procesos++;
            this.F1.setVisible(true);
            this.F2.setVisible(true);
            this.jLabel6.setVisible(true);
            if(this.algoritmo==3){
                this.F3.setVisible(true);
            }
            
        } else if (this.procesos == 6) {
            this.procesos++;
            this.G1.setVisible(true);
            this.G2.setVisible(true);
            this.jLabel7.setVisible(true);
            if(this.algoritmo==3){
                this.G3.setVisible(true);
            }
            
        } else if (this.procesos == 7) {
            this.procesos++;
            this.H1.setVisible(true);
            this.H2.setVisible(true);
            this.jLabel8.setVisible(true);
            if(this.algoritmo==3){
                this.H3.setVisible(true);
            }
            this.jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.procesos == 8) {
            this.procesos--;
            this.H1.setText("");
            this.H2.setText("");
            this.H3.setText("");
            this.H1.setVisible(false);
            this.H2.setVisible(false);
            this.H3.setVisible(false);
            this.jLabel8.setVisible(false);
            this.jButton1.setEnabled(true);   
            
        } else if (this.procesos == 7) {
            this.procesos--;
            this.G1.setText("");
            this.G2.setText("");
            this.G3.setText("");
            this.G1.setVisible(false);
            this.G2.setVisible(false);
            this.G3.setVisible(false);
            this.jLabel7.setVisible(false);
            
        } else if (this.procesos == 6) {
            this.procesos--;
            this.F1.setText("");
            this.F2.setText("");
            this.F3.setText("");
            this.F1.setVisible(false);
            this.F2.setVisible(false);
            this.F3.setVisible(false);
            this.jLabel6.setVisible(false);
            
        } else if (this.procesos == 5) {
            this.procesos--;
            this.E1.setText("");
            this.E2.setText("");
            this.E3.setText("");
            this.E1.setVisible(false);
            this.E2.setVisible(false);
            this.E3.setVisible(false);
            this.jLabel5.setVisible(false);
            this.jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        
    }//GEN-LAST:event_A1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField A3;
    private javax.swing.JTextField B1;
    private javax.swing.JTextField B2;
    private javax.swing.JTextField B3;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C2;
    private javax.swing.JTextField C3;
    private javax.swing.JTextField D1;
    private javax.swing.JTextField D2;
    private javax.swing.JTextField D3;
    private javax.swing.JTextField E1;
    private javax.swing.JTextField E2;
    private javax.swing.JTextField E3;
    private javax.swing.JTextField F1;
    private javax.swing.JTextField F2;
    private javax.swing.JTextField F3;
    private javax.swing.JTextField G1;
    private javax.swing.JTextField G2;
    private javax.swing.JTextField G3;
    private javax.swing.JTextField H1;
    private javax.swing.JTextField H2;
    private javax.swing.JTextField H3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
